### ISSUE TITLE
Bug: Files are not being evaluated properly

### ISSUE THREAD

**Issue by aamfahim** [SychAndrii/infusion#11]
I saw an error `NotSourceCodeError`, so in order to test it, in the example file, right on top, I put in unrelated texts (100 lines of it). First couple of times it was perfect, the result would only include documented source code, but after running it a couple of times I noticed sometimes it would work fine and other times it would throw the aforementioned error, which is inconsistent.

I think, if there's none code related stuff in the file provided, the error should always be raised. Or just parse the file extract the code only and then process it. But I leave the solution up to you.

**Comment by SychAndrii** [comment]
Thank you!
The problem was that I confused LLM with my prompt. I told it that I only want source code from it, and at the same time I told it to send the word 'error' if the code it read was not following language's syntax. Additionally, I rephrased my prompt to be more strict with files that do not contain valid code. You can see the pull request for the changes I added.
Closed with #19
